# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('day', models.IntegerField(choices=[(3, 3), (4, 4), (5, 5)])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('manual_time', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internt navn, f.eks. Aud. E', max_length=50, verbose_name='internt navn')),
                ('official_name', models.CharField(help_text='Officiel lokalebetegnelse, f.eks. 1535-128', max_length=50, verbose_name='officielt navn')),
                ('capacity', models.CharField(help_text='Kapacitetsbegrænsning', max_length=100, verbose_name='kapacitet')),
                ('kind', models.CharField(choices=[('auditorium', 'auditorium'), ('classroom', 'classroom'), ('hall', 'hall')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('kind', models.CharField(choices=[('rusclass', 'rusclass'), ('partner', 'partner')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='locations',
            field=models.ManyToManyField(blank=True, to='lokaleplan.Location'),
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, to='lokaleplan.Participant'),
        ),
    ]
