# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lokaleplan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.IntegerField(choices=[(3, 'onsdag'), (4, 'torsdag'), (5, 'fredag')]),
        ),
    ]
