# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lokaleplan', '0002_auto_20160701_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['day', 'start_time', 'name', 'end_time']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['kind', 'name']},
        ),
        migrations.AlterField(
            model_name='participant',
            name='kind',
            field=models.CharField(choices=[('rusclass', 'Hold'), ('partner', 'Andre')], max_length=10),
        ),
    ]
