# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 16:57
from __future__ import unicode_literals

from django.db import migrations


def rename_partner_events(apps, schema_editor):
    Event = apps.get_model('lokaleplan', 'Event')
    qs = Event.objects.filter(participants__kind='partner')
    for e in qs:
        e.name = e.participants.all()[0].name
        e.save()


class Migration(migrations.Migration):

    dependencies = [
        ('lokaleplan', '0003_misc_meta'),
    ]

    operations = [
        migrations.RunPython(rename_partner_events),
    ]
