# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 16:57
from __future__ import unicode_literals

from django.db import migrations


def remove_partner_participants(apps, schema_editor):
    Participant = apps.get_model('lokaleplan', 'Participant')
    qs = Participant.objects.filter(kind='partner')
    qs.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('lokaleplan', '0004_rename_partner_events'),
    ]

    operations = [
        migrations.RunPython(remove_partner_participants),
    ]
