# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lokaleplan', '0005_remove_partner_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='participant',
            name='kind',
        ),
    ]
