# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lokaleplan', '0006_remove_participant_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.IntegerField(choices=[(3, 'onsdag'), (4, 'torsdag'), (5, 'fredag')], verbose_name='dag'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(verbose_name='sluttid'),
        ),
        migrations.AlterField(
            model_name='event',
            name='locations',
            field=models.ManyToManyField(blank=True, to='lokaleplan.Location', verbose_name='lokaler'),
        ),
        migrations.AlterField(
            model_name='event',
            name='manual_time',
            field=models.CharField(blank=True, max_length=100, verbose_name='vist tid'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=50, verbose_name='navn'),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, to='lokaleplan.Participant', verbose_name='deltagere'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(verbose_name='starttid'),
        ),
    ]
